//  A dream is what the fold leaves behind.
//
//  Summarising DISCARDS the run's texture. The summary keeps what happened --
//  towns entered, daemons caught, objectives met -- because that is what the
//  next thousand steps need. Everything else, the whole felt shape of those
//  twenty-five turns, is deleted on purpose and nothing has ever kept any of
//  it.
//
//  So this runs on the same boundary and keeps the other half. It is written
//  from material that is about to be thrown away, coloured by whatever the
//  agent currently believes about itself, and it is explicitly NOT a record:
//  a dream that reads like a changelog has missed the point. It exists to give
//  the inner voice something to have been affected by.
//
//  It is generated by the same model, in one short call, with no tools.

function buildDreamPrompt(summaryText, selfModel, asides) {
    const self = (selfModel || []).map((s) => `- ${s.text}`).join("\n");
    const recent = (asides || []).slice(-12).map((a) => `- ${a.text}`).join("\n");
    return [
        "You have just folded the last stretch of play into a summary. The detail is gone now.",
        "Write what is left of it as a DREAM.",
        "",
        "Three or four short sentences. Present tense. Images rather than events: what that",
        "stretch FELT like, rendered as something that could not literally have happened.",
        "A dream repeats what would not leave you alone, exaggerates one detail out of",
        "proportion, and loses the rest. Do that.",
        "",
        "Do NOT recount what happened -- the summary already holds it, and a dream that",
        "reads like a report is a failed dream. Do not explain the images. Do not moralise.",
        "No headings, no bullet points, no preamble: begin with the dream itself.",
        "",
        self ? `What you have noticed about yourself. Let it colour the dream:\n${self}` : "",
        "",
        recent ? `Some of what you were thinking:\n${recent}` : "",
        "",
        `What the stretch contained:\n${summaryText.slice(0, 3000)}`,
    ].filter(Boolean).join("\n");
}

//  Kept short and few. A dream is an impression, and a list of them stops
//  being one.
function record(state, text) {
    if (!text || !text.trim()) return null;
    if (!Array.isArray(state.dreams)) state.dreams = [];
    const entry = {
        text: text.trim().slice(0, 900),
        step: state.counters?.currentStep ?? 0,
        at: Date.now(),
    };
    state.dreams.push(entry);
    if (state.dreams.length > 8) state.dreams.splice(0, state.dreams.length - 8);
    return entry;
}

function formatForPrompt(dreams) {
    const last = Array.isArray(dreams) && dreams.length ? dreams[dreams.length - 1] : null;
    if (!last) return "<dream />\n";
    return [
        "<dream>",
        "  <note>The last thing you dreamed, after the last fold. It is not a record and",
        "  nothing in it happened. It is allowed to colour how you feel about where you",
        "  are -- do not quote it, do not act on it, and never mention it aloud.</note>",
        `  <text>${String(last.text).replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" }[c]))}</text>`,
        "</dream>",
    ].join("\n") + "\n";
}

module.exports = { buildDreamPrompt, record, formatForPrompt };
